import type { LevelDef } from '../../../types/game';

export const boss3: LevelDef = {
  id: 'boss-3',
  world: 3,
  levelNum: 5,
  title: 'The Grand Deployment',
  subtitle: 'Orchestrate a full feature launch from start to finish',
  concept: 'Full orchestration — decompose, delegate, automate, review, ship',
  isBoss: true,

  narrativeIntro:
    'Sirens blare across the Cat Colony. Commander Whiskersworth bursts into the war room, his ' +
    'fur standing on end. "Code red, recruit! The Catnip Marketplace needs to launch by end of ' +
    'day — and we just lost three senior developers to a spontaneous napping incident." He slams ' +
    'the feature spec on the table. "The marketplace needs a product catalog, a shopping cart, ' +
    'order processing, and real-time inventory updates. You\'re not building this alone — you\'re ' +
    'ORCHESTRATING it. Decompose the feature, delegate to background agents, set up automations ' +
    'for the review pipeline, and personally review the final code before it ships." He pins a ' +
    'gold star to the mission board. "This is the full orchestration drill. Everything you\'ve ' +
    'learned in the Colony comes together here: task decomposition, background delegation, ' +
    'automated workflows, and code review. Do this right, and you earn the Crown — the highest ' +
    'honor in the Colony." He salutes. "The marketplace launches today, Commander. Make it happen."',

  briefing:
    'Launch the Catnip Marketplace by orchestrating the full workflow: decompose the feature, ' +
    'delegate to background agents, set up automated review pipelines, and review the final ' +
    'code. Complete all four phases.',

  challengeSteps: [
    {
      id: 'boss-3-main',
      type: 'multi_step',
      instruction:
        'Complete all four phases of the Grand Deployment to launch the Catnip Marketplace.',
      subSteps: [
        {
          id: 'boss-3-sub1',
          type: 'decompose_tasks',
          instruction:
            'Phase 1 — Decompose: Break the Catnip Marketplace into focused subtasks.\n\n' +
            '**Feature: Catnip Marketplace**\n' +
            '- Product catalog with categories and search\n' +
            '- Shopping cart with quantity management\n' +
            '- Order processing with payment integration\n' +
            '- Real-time inventory tracking and alerts\n\n' +
            'Break this into at least 3 independent subtasks.',
          featureDescription:
            'Build a catnip marketplace with product catalog, shopping cart, order processing, ' +
            'and real-time inventory tracking',
          minSubtasks: 3,
        },
        {
          id: 'boss-3-sub2',
          type: 'launch_background',
          instruction:
            'Phase 2 — Delegate: You have two tasks. The product catalog data models and API ' +
            'endpoints can be generated by a background agent. The shopping cart UI needs ' +
            'visual iteration and should stay local. Send the right task to the cloud.',
          cloudTask: 'Generate product catalog data models, database schema, and CRUD API endpoints with validation',
          localTask: {
            instruction: 'Build the shopping cart UI with add/remove buttons, quantity controls, and a running total',
            files: [
              {
                name: 'ShoppingCart.tsx',
                content: `// ShoppingCart.tsx
import { useState } from 'react';

interface CartItem {
  id: string;
  name: string;
  price: number;
  quantity: number;
}

export function ShoppingCart() {
  const [items, setItems] = useState<CartItem[]>([]);

  // TODO: implement add, remove, update quantity, calculate total
  return (
    <div className="cart">
      <h2>Your Cart</h2>
      <p>Cart is empty</p>
    </div>
  );
}`,
                language: 'typescriptreact',
              },
            ],
          },
        },
        {
          id: 'boss-3-sub3',
          type: 'setup_automation',
          instruction:
            'Phase 3 — Automate: Set up the review pipeline. Configure two automations:\n' +
            '• **Quality Gate Cat** — runs when a PR is opened, reviews for bugs and security\n' +
            '• **Deploy Watch Cat** — runs after deployment, monitors for errors in the first 30 minutes',
          automations: [
            {
              id: 'quality-gate-cat',
              name: 'Quality Gate Cat',
              triggerOptions: ['PR opened', 'Bug created', 'Daily schedule', 'Deploy completed', 'Manual trigger'],
              correctTrigger: 'PR opened',
              promptHint: 'Review the PR for security vulnerabilities, missing error handling, and potential bugs. Block merge if critical issues found.',
              requiredMcps: ['github'],
            },
            {
              id: 'deploy-watch-cat',
              name: 'Deploy Watch Cat',
              triggerOptions: ['PR opened', 'Bug created', 'Daily schedule', 'Deploy completed', 'Manual trigger'],
              correctTrigger: 'Deploy completed',
              promptHint: 'Monitor application logs for errors, check health endpoints, and alert the team if error rate exceeds 1% in the first 30 minutes.',
              requiredMcps: ['monitoring'],
            },
          ],
        },
        {
          id: 'boss-3-sub4',
          type: 'review_pr',
          instruction:
            'Phase 4 — Review: The agents\' work is done. Review the final PR before shipping. ' +
            'The order processing endpoint has a critical issue.',
          prs: [
            {
              id: 'marketplace-pr',
              title: 'Add order processing endpoint',
              diff: {
                fileName: 'routes/orders.ts',
                before:
`// routes/orders.ts
import { Router } from 'express';
const router = Router();

// TODO: implement order processing

export default router;`,
                after:
`// routes/orders.ts
import { Router } from 'express';
import { db } from '../database';
import { processPayment } from '../services/payment';
const router = Router();

router.post('/orders', async (req, res) => {
  const { userId, items, paymentMethod } = req.body;

  const total = items.reduce((sum: number, item: any) => sum + item.price * item.quantity, 0);

  const payment = await processPayment(paymentMethod, total);

  const order = await db.insert('orders', {
    userId,
    items: JSON.stringify(items),
    total,
    paymentId: payment.id,
    status: 'confirmed',
  });

  for (const item of items) {
    await db.query(
      'UPDATE inventory SET stock = stock - ? WHERE product_id = ?',
      [item.quantity, item.id]
    );
  }

  res.json({ data: order });
});

export default router;`,
                hasIssue: true,
                issueDescription:
                  'No transaction! The payment, order insertion, and inventory update are three ' +
                  'separate operations without a database transaction. If the inventory update fails ' +
                  '(e.g., insufficient stock), the payment has already been charged and the order ' +
                  'recorded — creating an inconsistent state. All three operations must be wrapped in ' +
                  'a transaction with proper rollback on failure.',
              },
              issueType: 'correctness',
              issueDescription:
                'Missing database transaction: payment, order creation, and inventory update should be atomic. A failure in any step leaves the system in an inconsistent state.',
            },
          ],
        },
      ],
    },
  ],

  debrief:
    'Mission accomplished, Commander! The Catnip Marketplace is shipping, and you orchestrated ' +
    'the entire deployment like a seasoned tech lead. Let\'s debrief:\n\n' +
    '1. **Decomposition** — You broke a complex feature into manageable, independent subtasks ' +
    'that agents could work on in parallel.\n' +
    '2. **Delegation** — You correctly sent the data-heavy backend work to a background agent ' +
    'and kept the visual UI work local where you could iterate quickly.\n' +
    '3. **Automation** — You set up a quality gate (PR review) and a safety net (deploy monitoring) ' +
    'that will catch issues automatically, day and night.\n' +
    '4. **Review** — You caught a critical atomicity bug: payment + order + inventory must be ' +
    'a single transaction, or a partial failure leaves the system in a broken state.\n\n' +
    'This is the full AI-assisted development lifecycle: plan → delegate → automate → review → ' +
    'ship. The human developer\'s role evolves from writing every line to orchestrating a team ' +
    'of AI agents — but the need for careful review and architectural judgment only grows.\n\n' +
    'Pro tip: the more automated your pipeline, the more important your review skills become. ' +
    'Automated agents amplify both your productivity AND your bugs if you\'re not careful.',

  realWorldMapping: 'Full AI-orchestrated development workflow: decompose, delegate, automate, review, ship',

  quiz: [
    {
      question: 'Why must payment processing, order creation, and inventory updates be in a single transaction?',
      options: [
        'Transactions make queries run faster',
        'Without a transaction, a failure in one step leaves the system in an inconsistent state (e.g., charged but not delivered)',
        'Databases require all write operations to be in transactions',
        'Transactions prevent SQL injection attacks',
      ],
      correctIndex: 1,
    },
    {
      question: 'What is the correct trigger for a post-deployment monitoring automation?',
      options: [
        'PR opened',
        'Daily schedule',
        'Deploy completed',
        'Bug created',
      ],
      correctIndex: 2,
    },
    {
      question: 'In the AI-assisted development lifecycle, what is the developer\'s most critical role?',
      options: [
        'Writing every line of code manually',
        'Orchestrating agents and carefully reviewing their output',
        'Configuring as many background agents as possible',
        'Deploying code as fast as possible to minimize downtime',
      ],
      correctIndex: 1,
    },
  ],

  reward: { xp: 150, accessory: 'crown', accessoryEmoji: '👑' },

  hints: [
    { text: 'Take each phase sequentially. Phase 1 decomposes, Phase 2 delegates, Phase 3 automates, Phase 4 reviews.', xpCost: 0 },
    { text: 'Phase 2: backend data work goes to the cloud, UI stays local. Phase 3: PR review triggers on PR opened, deploy monitoring triggers after deploy. Phase 4: look for atomicity issues in the order endpoint.', xpCost: 10 },
    { text: 'Phase 4: the order endpoint processes payment, creates an order, and updates inventory as separate operations without a transaction. If inventory update fails, the user is charged but gets nothing. Wrap in a transaction!', xpCost: 25 },
  ],

  parTimeSeconds: 600,
};
